// <auto-generated />
using System;
using HumanResources.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HumanResources.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708194851_mig_Update_Item")]
    partial class mig_Update_Item
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HumanResources.Entity.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AcilDurumKisiAdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcilDurumTelefonu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AmirId")
                        .HasColumnType("integer");

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<string>("CalismaDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FotografUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IstenAyrilisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KanGrubu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedeniDurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PersonelTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SgkSicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToplamKullanilanIzinGunu")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("VardiyaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AmirId");

                    b.HasIndex("BirimId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("VardiyaId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.AppUserEgitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminAciklamasi")
                        .HasColumnType("text");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BasvuruDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EgitimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EgitimId");

                    b.ToTable("AppUserEgitimler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("YoneticiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YoneticiId");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.DisiplinKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisiplinNedeni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IspatGorseliYolu")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("TanikAdSoyad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("DisiplinKayitlari");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durumu")
                        .HasColumnType("integer");

                    b.Property<string>("EgitimAciklamasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EgitimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Egitmen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SuresiSaat")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Izin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("AmirOnayi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IkOnayi")
                        .HasColumnType("boolean");

                    b.Property<int>("IzinTuruId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IzinTuruId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Izinler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.IzinTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<bool>("UcretliMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("IzinTurleri");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Sertifika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("AlinmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("BelgeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("text");

                    b.Property<int>("Durumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GecerlilikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SertifikaTuruId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("VerenKurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("YenilemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("SertifikaTuruId");

                    b.ToTable("Sertifikalar");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.SertifikaTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SertifikaTurleri");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AraDinlenmeSuresiDk")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("CalismaSuresi")
                        .HasColumnType("interval");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("YoneticiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YoneticiId");

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Zimmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Durumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marka")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriNumarasi")
                        .HasColumnType("text");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ZimmetTuruId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ZimmetTuruId");

                    b.ToTable("Zimmetler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.ZimmetTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ZimmetTurleri");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.AppUser", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "Amir")
                        .WithMany("BagliPersoneller")
                        .HasForeignKey("AmirId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HumanResources.Entity.Entities.Birim", "Birim")
                        .WithMany("Personeller")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.Departman", "Departman")
                        .WithMany("Personeller")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.Vardiya", "Vardiya")
                        .WithMany("Personeller")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Amir");

                    b.Navigation("Birim");

                    b.Navigation("Departman");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.AppUserEgitim", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "AppUser")
                        .WithMany("AppUserEgitims")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.Egitim", "Egitim")
                        .WithMany("Katilimcilar")
                        .HasForeignKey("EgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Egitim");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Birim", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.Departman", "Departman")
                        .WithMany("Birimler")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Departman", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "Yonetici")
                        .WithMany()
                        .HasForeignKey("YoneticiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.DisiplinKaydi", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "AppUser")
                        .WithMany("DisiplinKayitlari")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Izin", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.IzinTuru", "IzinTuru")
                        .WithMany("Izinler")
                        .HasForeignKey("IzinTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.AppUser", "Personel")
                        .WithMany("Izinler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IzinTuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Sertifika", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "AppUser")
                        .WithMany("Sertifikalar")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.SertifikaTuru", "SertifikaTuru")
                        .WithMany("Sertifikalar")
                        .HasForeignKey("SertifikaTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("SertifikaTuru");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Vardiya", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "Yonetici")
                        .WithMany()
                        .HasForeignKey("YoneticiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Zimmet", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", "AppUser")
                        .WithMany("Zimmetler")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.ZimmetTuru", "ZimmetTuru")
                        .WithMany("Zimmetler")
                        .HasForeignKey("ZimmetTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("ZimmetTuru");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResources.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HumanResources.Entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.AppUser", b =>
                {
                    b.Navigation("AppUserEgitims");

                    b.Navigation("BagliPersoneller");

                    b.Navigation("DisiplinKayitlari");

                    b.Navigation("Izinler");

                    b.Navigation("Sertifikalar");

                    b.Navigation("Zimmetler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Birim", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Departman", b =>
                {
                    b.Navigation("Birimler");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Egitim", b =>
                {
                    b.Navigation("Katilimcilar");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.IzinTuru", b =>
                {
                    b.Navigation("Izinler");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.SertifikaTuru", b =>
                {
                    b.Navigation("Sertifikalar");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.Vardiya", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("HumanResources.Entity.Entities.ZimmetTuru", b =>
                {
                    b.Navigation("Zimmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
